app = "expo-fast"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[image]
  ref = "tkejr/expo-fast:latest"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  protocol = "tcp"
  internal_port = 8001

  [[services.ports]]
    port = 8001
    handlers = ["http"]

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2 