name: Deploy Supabase to Staging

on:
  push:
    branches:
      - dev
    paths:
      - 'supabase/**'  # Only trigger when Supabase files change
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy-supabase-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Verify Supabase CLI installation
        run: supabase --version

      - name: Link to Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_STAGING_PROJECT_ID }}
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Push migrations to staging
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "🚀 Pushing Supabase migrations to staging..."
          supabase db push

      - name: Verify migration status
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "📊 Checking migration status..."
          supabase migration list

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Successfully deployed Supabase migrations to staging environment"
          echo "Environment: staging"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "🗄️ Database migrations have been applied"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Failed to deploy Supabase migrations to staging environment"
          echo "Please check the logs above for more details"
          echo "Common issues:"
          echo "- Invalid SUPABASE_ACCESS_TOKEN"
          echo "- Wrong SUPABASE_STAGING_PROJECT_ID"
          echo "- Migration conflicts"
          echo "- Network connectivity issues" 